### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by FreezerMoosh** [Nekeras/Permissions-GUI#1]
Not sure if this is active but where is the link

**Comment by Nekeras** [comment]
No, sadly this project isn't active anymore. I wouldn't recommend this very old version anyway, because I was very unexperienced in programming with Java back then.
I am working on a Remake since a year now, but I am very busy at the moment.
The new version should act as a Plugin, the User Interface can be accessed using the local browser.

If the core mechanics are implemented, I'll make the project open source, but this might take awhile, since I don't have as much time as four years ago.
If everything goes right, I should be able to publish the new version in three to five months.

**Comment by FreezerMoosh** [comment]
Okay, local browser would be cool but how would it work on a host online?

**Comment by Nekeras** [comment]
The plugin will start an own HTTP server which will run on a custom port such like 8080, for example. You will be able to configure remote access and can then connect to your server using port 8080 to access the user interface. 
Of course this will also work on a local machine, then you can just connect to localhost:8080.

**Comment by FreezerMoosh** [comment]
Nice idea! Looking forward to that
